[package]
authors = ["Daniel Kolsoi <thadan64@gmail.com>"]
description = ""
edition = "2024"
license = "Apache-2.0"
name = "pupman"
readme = "README.md"
version = "0.1.0"

[dependencies]
etc-passwd = "0.2.2"
nix = "0.30.1"
tempfile = "3.2"
